version: 2

python:
  version: 3.10
  install:
    - requirements: requirements.txt

build:
  os: ubuntu-22.04
  tools:
    mkdocs: {}   # <-- qui MkDocs viene registrato correttamente come tool

mkdocs:
  configuration: mkdocs.yml
